### ISSUE TITLE
Annotations styles not working

### ISSUE THREAD

**Issue by aikruger** [ycnmhd/obsidian-enhanced-annotations#12]
It seems for some reason I cannot identify the style settings are no longer being applied to the annotations. Any help appreciated

**Comment by ycnmhd** [comment]
Could it be that the plugin is idle?

**Comment by aikruger** [comment]
Very strange I had to highlight, using ==, a section on a note and then it suddenly started working perfectly. Thanks

**Comment by ycnmhd** [comment]
The plugin uses signals to detect that it's being used, such as 
- The user interacting with the side bar view
- Files having labeled comments (such as `<!--label: ...-->`)

If the plugin does not receive these signals in 3 days, it goes into idle mode to save processing power.
